# FAULT INJECTION

# Feature in Istio that allows to simulate failures within the service mesh to test the resilience of services.
# By deliberately introducing faults like delays or errors, you can observe how your system behaves under adverse conditions and ensure that your applications can tolerate failures gracefully.

# - Delays: Introduce artificial delays to simulate network latency.
# - Abort/Errors: Simulate HTTP or gRPC errors to test how services handle failed requests.

# Simulating a DELAY
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-service
spec:
  hosts:
    - my-service
  http:
    - fault:
        delay:
          percent: 50         # 50% of requests will be delayed
          fixedDelay: 5s      # Delay of 5 seconds
      route:
        - destination:
            host: my-service
            subset: v1

---

# Simulating an ERROR
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-service
spec:
  hosts:
    - my-service
  http:
    - fault:
        abort:
          percent: 10           # 10% of requests will return an error
          httpStatus: 500       # Return HTTP 500 error code
      route:
        - destination:
            host: my-service
            subset: v1
